### PR TITLE
updated to new spikeextractors 0.4.0

### PR DESCRIPTION
**Pull request by alejoe91**
@magland we are refractoring spikeinterface to snake case. This patch updates the calls to spikeextractors objects to the new functions.

For now spiketoolkit tests pass because we install my patched fork, so no rush :)

### CODE REVIEW

**Comment by tjd2002** [comment]
@magland Do we want to cut a new release for this?

**Comment by magland** [comment]
Thanks Tom. I just bumped the version and pushed -- so hopefully travis
publishes the new version.
Jeremy

**Comment by tjd2002** [comment]
I think we also need to add the dependency on 'spikeextractors' back to the setup.py file, since this patch removes the plug_spikeextractors copy of that code.

**Comment by magland** [comment]
okay, could you do that, pls?

**Comment by tjd2002** [comment]
Yup!

**Pull request merged**
